### ISSUE TITLE
Hitting: FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by josoroma-zz** [LimEunSeop/docker-react-apollo-prisma#1]
![image](https://user-images.githubusercontent.com/69951/132113433-509ebfe2-671c-45eb-838d-7342ff49874f.png)

```
#
# https://docs.docker.com/compose/compose-file
#
version: "3.8"

services:
  web:
    env_file:
      - ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    # links:
    #   - db
    command: ["./wait-for-it.sh", "db:5432", "--", "bash", "-c", "npm start"]
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: "/usr/src/app"
    volumes:
      - ./web/server:/usr/src/app/server
      - ./web/client/src:/usr/src/app/client/src
    #
    # https://docs.docker.com/compose/environment-variables
    #
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3001
      - DATABASE_URL=postgresql://postgres:password@db/dev
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=dev
  db:
    #
    # https://www.postgresql.org
    #
    image: postgres:13.4
    container_name: postgres13_4
    # user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
```
